=== smile-fifteen/-2104/lab-files/lab3/需求更改代码/74/code/xml.schema.completion/test/unit/src/org/netbeans/modules/xml/schema/completion/resources/PO.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://xml.netbeans.org/schema/PO"
    elementFormDefault="qualified" xmlns:tns="http://xml.netbeans.org/schema/PO">

  <xsd:annotation>
    <xsd:documentation xml:lang="en">
     Purchase order schema for Example.com.
     Copyright 2000 Example.com. All rights reserved.
    </xsd:documentation>
  </xsd:annotation>

  <xsd:element name="purchaseOrder" type="tns:PurchaseOrderType"/>

  <xsd:element name="comment" type="xsd:string"/>

  <xsd:complexType name="PurchaseOrderType">
    <xsd:sequence>
      <xsd:element name="shipTo" type="tns:USAddress"/>
      <xsd:element name="billTo" type="tns:USAddress"/>
      <xsd:element ref="tns:comment" minOccurs="0"/>
      <xsd:element name="items"  type="tns:Items"/>
    </xsd:sequence>
    <xsd:attribute name="orderDate" type="xsd:date"/>
  </xsd:complexType>

  <xsd:complexType name="USAddress">
    <xsd:sequence>
      <xsd:element name="name"   type="xsd:string"/>
      <xsd:element name="street" type="xsd:string"/>
      <xsd:element name="city"   type="xsd:string"/>
      <xsd:element name="state"  type="tns:States"/>
      <xsd:element name="zip"    type="xsd:decimal"/>
    </xsd:sequence>
    <xsd:attribute name="country" type="xsd:NMTOKEN"
                   fixed="US"/>
  </xsd:complexType>

  <xsd:complexType name="Items">
    <xsd:sequence>
      <xsd:element name="item" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="productName" type="xsd:string"/>
            <xsd:element name="quantity">
              <xsd:simpleType>
                <xsd:restriction base="xsd:positiveInteger">
                  <xsd:maxExclusive value="100"/>
                </xsd:restriction>
              </xsd:simpleType>
            </xsd:element>
            <xsd:element name="USPrice"  type="xsd:decimal"/>
            <xsd:element ref="tns:comment"   minOccurs="0"/>
            <xsd:element name="shipDate" type="xsd:date" minOccurs="0"/>
          </xsd:sequence>
          <xsd:attribute name="partNum" type="tns:SKU" use="required"/>
          <xsd:attribute name="brand" type="tns:Brand" use="required"/>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <!-- Stock Keeping Unit, a code for identifying products -->
  <xsd:simpleType name="SKU">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="\d{3}-[A-Z]{2}"/>
    </xsd:restriction>
  </xsd:simpleType>
  
  <xsd:simpleType name="Brand">
    <xsd:restriction base="xsd:string">
        <xsd:enumeration value="ACER"/>
        <xsd:enumeration value="HP"/>
        <xsd:enumeration value="NOKIA"/>
        <xsd:enumeration value="SAMSUNG"/>
        <xsd:enumeration value="SONY"/>
        <xsd:enumeration value="SUN"/>
    </xsd:restriction>
  </xsd:simpleType>  
  
  <xsd:simpleType name="States">
    <xsd:restriction base="xsd:string">
        <xsd:enumeration value="AL"/>
        <xsd:enumeration value="AK"/>
        <xsd:enumeration value="AZ"/>
        <xsd:enumeration value="AR"/>
        <xsd:enumeration value="CA"/>
        <xsd:enumeration value="CO"/>
        <xsd:enumeration value="CT"/>
        <xsd:enumeration value="DE"/>
        <xsd:enumeration value="FL"/>
        <xsd:enumeration value="GA"/>
        <xsd:enumeration value="HI"/>
        <xsd:enumeration value="ID"/>
        <xsd:enumeration value="IL"/>
        <xsd:enumeration value="IN"/>
        <xsd:enumeration value="IA"/>
        <xsd:enumeration value="KS"/>
        <xsd:enumeration value="KY"/>
        <xsd:enumeration value="LA"/>
        <xsd:enumeration value="ME"/>
        <xsd:enumeration value="MD"/>
        <xsd:enumeration value="MA"/>
        <xsd:enumeration value="MI"/>
        <xsd:enumeration value="MN"/>
        <xsd:enumeration value="MS"/>
        <xsd:enumeration value="MO"/>
        <xsd:enumeration value="MT"/>
        <xsd:enumeration value="NE"/>
        <xsd:enumeration value="NV"/>
        <xsd:enumeration value="NH"/>
        <xsd:enumeration value="NJ"/>
        <xsd:enumeration value="NM"/>
        <xsd:enumeration value="NY"/>
        <xsd:enumeration value="NC"/>
        <xsd:enumeration value="ND"/>
        <xsd:enumeration value="OH"/>
        <xsd:enumeration value="OK"/>
        <xsd:enumeration value="OR"/>
        <xsd:enumeration value="PA"/>
        <xsd:enumeration value="RI"/>
        <xsd:enumeration value="SC"/>
        <xsd:enumeration value="SD"/>
        <xsd:enumeration value="TN"/>
        <xsd:enumeration value="TX"/>
        <xsd:enumeration value="UT"/>
        <xsd:enumeration value="VT"/>
        <xsd:enumeration value="VA"/>
        <xsd:enumeration value="WA"/>
        <xsd:enumeration value="WV"/>
        <xsd:enumeration value="WI"/>
        <xsd:enumeration value="WY"/>
    </xsd:restriction>
  </xsd:simpleType>

</xsd:schema>

=== smile-fifteen/-2104/lab-files/lab3/需求更改代码/73/code/xml.schema.completion/test/unit/src/org/netbeans/modules/xml/schema/completion/resources/PO9.xml
<?xml version="1.0" encoding="UTF-8"?>

<purchaseOrder  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xmlns="http://xml.netbeans.org/schema/PO"
   xsi:schemaLocation="http://xml.netbeans.org/schema/PO PO.xsd">
    <shipTo country="US">
        <name></name>
        <street></street>
        <city></city>
        <state></state>
        <zip></zip>
    </shipTo>
    <billTo country="US">
        <name></name>
        <street></street>
        <city></city>
        <state></state>
        <zip></zip>
    </billTo>
    <comment></comment>
    <items>
        <item partNum="" brand="">
            <productName></productName>
            <quantity></quantity>
            <USPrice></USPrice>
            <comment></comment>
            <shipDate></shipDate>
        </item>
    </items>
</purchaseOrder>
